// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY730O7GT5BidCh4T8rFKkKxkiXZNttYA',
    appId: '1:340118958004:web:33fd6a5784242003c68ce1',
    messagingSenderId: '340118958004',
    projectId: 'focus-fitness-90f35',
    authDomain: 'focus-fitness-90f35.firebaseapp.com',
    storageBucket: 'focus-fitness-90f35.firebasestorage.app',
    measurementId: 'G-KXHWJ19JPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2ZRNcgFWvLQRIg4iJICnlCsDlWBOy0Zs',
    appId: '1:419558554401:android:9efc1a1b16b88ecb8fdc60',
    messagingSenderId: '419558554401',
    projectId: 'focus-fusion-notification',
    storageBucket: 'focus-fusion-notification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnjlPWdDfLzwkJLU-er9hXE1ciys9Gtdk',
    appId: '1:419558554401:ios:ee8653a6157b31358fdc60',
    messagingSenderId: '419558554401',
    projectId: 'focus-fusion-notification',
    storageBucket: 'focus-fusion-notification.firebasestorage.app',
    androidClientId: '419558554401-e4sstf9vtg8nd3mgjjks22kq0l1f4apo.apps.googleusercontent.com',
    iosClientId: '419558554401-e708jbphftuhc28bltbgkf2lasr547t2.apps.googleusercontent.com',
    iosBundleId: 'com.focusfitness.fitt',
  );

}