// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY730O7GT5BidCh4T8rFKkKxkiXZNttYA',
    appId: '1:340118958004:web:33fd6a5784242003c68ce1',
    messagingSenderId: '340118958004',
    projectId: 'focus-fitness-90f35',
    authDomain: 'focus-fitness-90f35.firebaseapp.com',
    storageBucket: 'focus-fitness-90f35.firebasestorage.app',
    measurementId: 'G-KXHWJ19JPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtoyAjO6Ym_EtjbKYZPrXFhvVnQFydYKA',
    appId: '1:340118958004:android:209b6b6deaba20e9c68ce1',
    messagingSenderId: '340118958004',
    projectId: 'focus-fitness-90f35',
    storageBucket: 'focus-fitness-90f35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWk9LC4zuUoK3qj3ZHhTe1D3MZXKuCmKw',
    appId: '1:340118958004:ios:4acc07bec990dbe6c68ce1',
    messagingSenderId: '340118958004',
    projectId: 'focus-fitness-90f35',
    storageBucket: 'focus-fitness-90f35.firebasestorage.app',
    iosBundleId: 'com.example.focusFitness',
  );
}
